apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cgwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cgwz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cgwz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cgwz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cgwz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-thzf-tenant/rhtap-demo-app/hacbs-test-project-cgwz@sha256:ec623b07cd818ceba545da64d0a36963079542678480e8d0345e9853146b04d7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
